### ISSUE TITLE
padding issue

### ISSUE THREAD

**Issue by artemana** [Wedjaa/JavaAnsibleVault#3]
There seem to be a bug in this implementation. 

This peace contains fix to it
`public byte[] pad(byte[] cleartext) throws IOException {
        byte[] padded = null;

        try {
            int blockSize = Cipher.getInstance(CYPHER_ALGO).getBlockSize();
            logger.debug("Padding to block size: {}", blockSize);
            int padding_length = (blockSize - (cleartext.length % blockSize));
            if (padding_length == 0) {
                padding_length = blockSize;
            }
            padded = Arrays.copyOf(cleartext, cleartext.length + padding_length);
            
            for(int a=padding_length + cleartext.length - 1;a>=cleartext.length;a--) {
            	padded[a] = (byte) padding_length;
            }
            
        } catch (Exception ex) {
            throw new IOException("Error calculating padding for " + CYPHER_ALGO + ": " + ex.getMessage());
        }

        return padded;
    }`

**Comment by Wedjaa** [comment]
Hi,

zerolength padding defines the padding as:

> ZeroLength. This pads with zeros except for the last byte which is equal to the number (length) of padding bytes.

So the implementation is correct.
